ynyJEFBERGVBRFJK V RFVRFR
  GRNFHRBHJFBRNGFJKRGR
    RMGJRNKGRFMKLT B
      FRNJFKBRJV JNBJKFNB FV
        F
          V,.RFM VKRF VKLMFVFv
            F,VJKJBFVN FVDF?V
              '.F,KVBJFNVKL;D.V
              RF/VMNRFJKNVD/V';FLNVDM,C.
              D',VMJKFBVND'
              V/.,FLKJVD';V,M RFKBN 3